### ISSUE TITLE
Cell model design

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/fractions-intro#33]
@samreid and I discussed potential initial implementations. Here's a first draft of how things would potentially work:

Model:

Cell
- isFilledProperty `@public {Property.<boolean>}` - Whether the cell is visually filled in.
- incomingPieceProperty `@public {Property.<Piece|null>}` - If it exists, the piece that is animating towards this cell to fill it.
- distanceTo `@abstract @public function( {Vector2} ) : {number}` - Distance from the cell to a model point
- (possibly if helpful) position `@public {Vector2}` instead of distanceTo. May simplify animating pieces

PieCell / CakeCell inherits Cell
- rotation `{number}` and/or startAngle/endAngle `{number}` or an enumeration of possible Cake angles, depending on what works better.

RectangularCell inherits Cell
- bounds `@public {Bounds2}` - Model bounds relative to the container's offset that it will take up.

Container( denominatorProperty: {Property.<number>} )
- cells `@public {ObservableArray.<Cell>}` - All of the cells that exist. Will be cleared and filled with new cells whenever the denominator changes (easier to have un-changing bounds/rotations/angles/positions on the cells themselves).
- visibleProperty `@public {Property.<boolean>}` - Whether the container is shown (may not be visible if the max is low enough)
- position `@public {Property.<Vector2>}` - Model position of the center of the container. All cells are offset from this position. ContainerSet is responsible for changing this when the number of containers changes, so that it is centered.
- getClosestEmptyCell `@public function( {Vector2} ) : {Cell|null}` - Find the closest empty (not filled and doesn't have a cell animating to it) cell to a given model location, if there is one
- getNextEmptyCell `@abstract @public function() : {Cell|null}` - Returns the next empty cell to be filled when increasing the numerator.
- getNextFilledCell `@abstract @public function() : {Cell|null}` - Returns the next filled cell to be removed when decreasing the numerator.

PieContainer / CakeContainer / (names for rectangular ones?) inherits Container
- Controls the add/remove order, z-order (if necessary) and model positioning of its cells, along with handling creation and mutation.

ContainerSet( containers: `{Array.<Container>}`, numeratorProperty: `{Property.<number>}`, denominatorProperty: `{Property.<number>}` )
- (pass in containers of the specific visual type, since all container sets have the same logic)
- containers `@public {Array.<Container>}` - All of the containers. May contain containers that are not visible, depending on the 'max'
- Listens to numerator/denominator, controlling the visibility/position of containers, and handling filling/unfilling cells, and the creation/destruction of Pieces.
- getClosestEmptyCell `@public function( {Vector2} ) : {Cell|null}` - Find the closest empty (not filled and doesn't have a cell animating to it) cell to a given model location, if there is one
- (IF handling piece logic here) pieces `@public {ObservableArray.<Piece>}`, and may need to be passed in ways to create/destroy pieces.

Piece
- destinationCell `@public {Property.<Cell|null>}` - If we're released and animating to a cell? Can be different from the "closest" empty Cell, which wi
- userControlled `@public {Propery.<boolean>}`
- position `@public {Property.<Vector2>}`

View has potentially subtypes for each cell (PieCellNode, CakeCellNode, RectangularCellNode), and equivalent subtype specific container nodes. Has a `{ModelViewTransform2}` for mapping between model coordinates and view coordinates.

@samreid, do you mind reviewing to make sure this looks good?

**Comment by veillette** [comment]
@michaelm396, @davisv007, @coledu: check off the boxes as you adress issues 

Model:

Cell
 - [x] isFilledProperty `@public {Property.<boolean>}` - Whether the cell is visually filled in.
 - [x] incomingPieceProperty `@public {Property.<Piece|null>}` - If it exists, the piece that is animating towards this cell to fill it.
 - [x] distanceTo `@abstract @public function( {Vector2} ) : {number}` - Distance from the cell to a model point
 - [x] (possibly if helpful) position `@public {Vector2}` instead of distanceTo. May simplify animating pieces

PieCell / CakeCell inherits Cell
-  [ ] rotation `{number}` and/or startAngle/endAngle `{number}` or an enumeration of possible Cake angles, depending on what works better.

RectangularCell inherits Cell
- [ ] bounds `@public {Bounds2}` - Model bounds relative to the container's offset that it will take up.

Container( denominatorProperty: {Property.<number>} )
- [ ] cells `@public {ObservableArray.<Cell>}` - All of the cells that exist. Will be cleared and filled with new cells whenever the denominator changes (easier to have un-changing bounds/rotations/angles/positions on the cells themselves).
- [ ] visibleProperty `@public {Property.<boolean>}` - Whether the container is shown (may not be visible if the max is low enough)
- [x] position `@public {Property.<Vector2>}` - Model position of the center of the container. All cells are offset from this position. ContainerSet is responsible for changing this when the number of containers changes, so that it is centered.
- [x] getClosestEmptyCell `@public function( {Vector2} ) : {Cell|null}` - Find the closest empty (not filled and doesn't have a cell animating to it) cell to a given model location, if there is one
- [x] getNextEmptyCell `@abstract @public function() : {Cell|null}` - Returns the next empty cell to be filled when increasing the numerator.
- [x] getNextFilledCell `@abstract @public function() : {Cell|null}` - Returns the next filled cell to be removed when decreasing the numerator.

PieContainer / CakeContainer / (names for rectangular ones?) inherits Container
- [ ] Controls the add/remove order, z-order (if necessary) and model positioning of its cells, along with handling creation and mutation.

ContainerSet( containers: `{Array.<Container>}`, numeratorProperty: `{Property.<number>}`, denominatorProperty: `{Property.<number>}` )
- [ ] (pass in containers of the specific visual type, since all container sets have the same logic)
- [x] containers `@public {Array.<Container>}` - All of the containers. May contain containers that are not visible, depending on the 'max'
- [ ]Listens to numerator/denominator, controlling the visibility/position of containers, and handling filling/unfilling cells, and the creation/destruction of Pieces.
- [x] getClosestEmptyCell `@public function( {Vector2} ) : {Cell|null}` - Find the closest empty (not filled and doesn't have a cell animating to it) cell to a given model location, if there is one
- [ ] (IF handling piece logic here) pieces `@public {ObservableArray.<Piece>}`, and may need to be passed in ways to create/destroy pieces.

Piece
- [x] destinationCell `@public {Property.<Cell|null>}` - If we're released and animating to a cell? Can be different from the "closest" empty Cell, which wi
- [ ] userControlled `@public {Propery.<boolean>}`
- [x] position `@public {Property.<Vector2>}`

**Comment by davisv7** [comment]
Made a commit that added a couple of these methods and attributes to the program.

**Comment by samreid** [comment]
I reviewed @jonathanolson's proposal.  Everything looks good, here are some minor comments:

Cell.incomingPieceProperty will be used in the following scenario: A user taps the up numerator spinner to send a piece to the cell.  Then while the piece is animating, the user taps the down numerator spinner.  We may use the Cell.incomingPieceProperty to know which piece was animating to the cell so it may animate back to the bucket.

Cell.distanceTo vs Cell.position.  To me, it seems more straightforward to use Cell.position.

> RectangularCell inherits Cell
> - bounds `@public {Bounds2}` - Model bounds relative to the container's offset that it will take up.

@jonathanolson can you elaborate what that is for?  Is it just for the view?

> Container( denominatorProperty: {Property.<number>} )

The `denominatorProperty` will be an argument to that constructor (not showing up as checkbox items above).  Same goes for the other constructors in @jonathanolson's comment.

Keep in mind all properties will end with the `Property` suffix.

**Comment by samreid** [comment]
I guess my last comment is about: `position @public {Property.<Vector2>}` which should probably be positionProperty.

**Comment by jonathanolson** [comment]
> Cell.distanceTo vs Cell.position. To me, it seems more straightforward to use Cell.position.

Sounds fine. Presumably then for things like cake/pie pieces, the position will need to be visually in the center, so both cells and pieces would presumably want to share the same offset information.

> @jonathanolson can you elaborate what that is for? Is it just for the view?

RectangularCell's bounds would be its visual bounds taken up? Each cell that is rectangular is displayed with a rectangle, and that rectangle's bounds (in model coordinates) would presumably be stored in the model.

**Comment by jonathanolson** [comment]
The main model differs fairly significantly from the recommended approach above, so I did a quick prototype this afternoon and tonight so I could recommend a good model structure. (Implemented 3 scenes with all interactive features I'm aware of, see http://www.colorado.edu/physics/phet/dev/olsonjb/fractions-intro_en.html). It's checked into the 'proto' branch, and has a fairly cleaned-up model (with a rough and not-yet-deduplicated and very rough view), and the prototype model may be worth review.

Some of my recommendations above definitely missed the mark.

Some suggestions based on that:

- Position does NOT belong in the model. The model should be the abstract representation with cells. Different views will have different positions/etc.
- This also means no storing bounds/rotations/etc. on cells, and no PieCell/RectangularCell/etc. recommended above.
- Instead, I recommend using an 'index' that, together with the denominator, determines each cell's view location/appearance in the view. Each view can determine view-specific things (position/rotation/image) from this index.
- I don't see the benefit of separating ContainerSet out of the main model. I combined the two in my prototype.
- Having a Property in Container that always has the number of filled cells was very helpful.
- I haven't found a need for an Emitter yet, but I'm open for arguments if it simplifies things. If Emitters are to be kept in the main code, please make a good argument why it's better than my prototype.
- Laying out the container views with an HBox seems totally acceptable, since it seems fine to clear animating pieces with a denominator/max change.
- To deal with rotating pieces (both in animations, and while dragging), it was very convenient to have cells/pieces have a "midpoint" concept, which is the point they rotate around. Doing this by bounds doesn't work well with circular segments
- Having containers be created and deleted was more convenient. I recommend removing Container's visibileProperty and changing model/containerset to have a containers ObservableArray as changes in https://github.com/phetsims/fractions-intro/issues/33
- It was helpful to handle the piece logic in the model. Some representations (beaker/line) don't create pieces (in the normal manner), so having an easy way to ignore piece creation is helpful (workaround in prototype is by immediately "completing" added pieces".
- For performance with the circle/cake forms, it seems best to only check what the "closest" cell to our dragged piece when we are dragging it (not for all pieces).
- I noticed some input oddities, like the numerator not changing immediately when pieces are dropped, etc. Checking over the input handling (mainly behavior, but my code also shows the patterns I've described) would be helpful.
- The prototype actually doesn't allow starting a drag on an animating piece. This may be convenient, and actually results in the pattern where the drag listener is NOT added to any nodes. It's weird, but it simplifies things.
- Understanding the model's changingInternally flag in the prototype may be very helpful. Some changes to the model's numerator are external (spinners), and extra action is required to make the model's state consistent with that. Other changes to the numerator are internal (we just filled a cell that the user dropped a piece on) where there is no extra action required. Ideally we'd have a better pattern that didn't rely on a flag, but this works.
- The Piece having both the to/from cell references is super helpful, not implementing my "only to" recommendation above was good.
- I see lots of computation of the actual fraction (numerator/denominator) in the code. I almost never needed that (except for determining whether spinner buttons are enabled). What is the benefit of that?

If it's helpful, I can implement the remaining scenes (and clean up view code) and then look into how best to handle the structure in the view.

**Comment by veillette** [comment]
@jonathanolson. This is very impressive. we should talk in depth Monday to get your input on what lessons we should heed from your prototype.

**Comment by samreid** [comment]
@jonathanolson this looks great.  I'm not sure what your plan is for moving forward or what the status of the prototype codebase is, but would it be suitable for @veillette and his team to use that code?

**Comment by coledu** [comment]
@samreid, we are planning to use @jonathanolson proto code as the master branch and incorporate our view component code into his model once we understand, comment, and clean it up. Since the performance is dramatically improved and his code is divided up into a more sensible fashion we deciding after our meeting to use his code instead of rectifying ours.

**Comment by samreid** [comment]
That sounds like a good plan, thanks!

**Comment by veillette** [comment]
@jonathanolson  and our group discussed what is the best way forward. As @coledu mentionned we decided to focus our work on the prototype.

We have merged the prototype into master. The prototype  and intro have separate Screens. They do not share any components. In the long term, we will like to deprecate the intro screen but for the time being we will keep it as a reference. It contains many visual elements that will be useful. Our efforts will be focused on the proto screen.
