### ISSUE TITLE
ContainerSet's containersEmitter

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/fractions-intro#61]
What is it? I'm not sure from the name, and it doesn't have documentation.

**Comment by michaelm396** [comment]
The containersEmitter, first initialized in ContainerSet, is a public object which signals once a container and/or cell has been updated. This is important because it signals to the Screen View an update to the fill property of a container or cell. I have refactored the name of the object to 'updatedContainersEmitter' in order to more closely resemble its functionality. I have also added documentation to ContainerSet that further describes the function of the object. Im assigning this issue back to @jonathanolson for further review. Thanks. (updated push: 2e527ed91a9b5fdaca570cfb157a5e5995355b3d)

**Comment by jonathanolson** [comment]
It's a bit weird that an emitter is being used as a flag to update things like this. Is it there so that there is only one visual update per frame?

I'm leaving assigned to myself for more review.

**Comment by veillette** [comment]
There is no longer any Emitter in the simulation and we do not intend to use one.
