### ISSUE TITLE
What screens should be included in full Fraction Intro sim?

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/fractions-intro#66]
Long ago, when I discussed the HTML5 version with Karina, it was suggested that teachers would find the "Fraction Lab" quite useful, and I believe this idea was backed up by some classroom observations. 

So it seems a natural progression of screens might be Intro, Equality, Lab

If we also want to include a game, we decided long ago that Fraction Matcher should not be included, but another possibility would be:

Intro, Equality, Lab, Game (where the game is "Build a Fraction") and we also publish Build a Fraction as a separate game

It would probably be good to decide if we are planning to include the "Fraction Lab" screen as it might help Martin and his team make some decisions as they move forward. 

Thoughts @kathy-phet and @amanda-phet?

**Comment by amanda-phet** [comment]
It seems to me that the Equality Lab pairs well with Fraction Matcher, so I would keep those together. 

I'm not sure I understand how the Fraction Lab screen is supposed to be used, but it seems like it pairs well with the Build a Fraction games. 

For this sim (Fractions Intro), I think a good progression could be Intro, Lab (Maybe?), Build a Fraction, Build a Mixed Fraction. 

We should probably have a design meeting at some point about this sim!

**Comment by ariel-phet** [comment]
@amanda-phet I am not sure I follow exactly... Fraction Matcher is already its own HTML5 sim with no planned changes, so the "Equality Lab" now only exists in the Java Fractions Intro sim. 

My understanding (and it may be good to check with Karina) is that teachers used the Fraction Lab screen in front of the class to compare/contrast various representations and allow discussion questions.

**Comment by amanda-phet** [comment]
I realize Fraction Matcher is already its own sim and almost proposed that we add the Equality Lab screen to it, but I know that wouldn't be a popular idea. When you pulled out that game into a single sim I wasn't sure what the plans were for the future. 

I would definitely talk to Karina about this. She used the sims in a classroom study (I believe it was a custom sim) and that's probably where you got the idea to include the Fraction Lab in this sim, so it would be good to find out how she saw teachers using that tab. 

Perhaps the progression should be: Intro, Equality, Lab, and you should keep the two Build a Fraction games as a separate game sim (like Fraction Matcher).

**Comment by ariel-phet** [comment]
@amanda-phet can you touch base with Karina (ideally before Thursday)

**Comment by krhensberry** [comment]
Hi folks,
Sorry for the delay. I've been traveling. 
In the Fractions study, we did have a custom sim per the teachers' request. It included the following screens; Intro, BAF, Equality Lab, Matching, and the Fraction Lab (from BAF sim). 
The teachers really liked the Fraction Lab. From the paper I wrote on this: "The Fraction
Lab screen was not originally included in Fractions Intro, but rather was the
third screen in PhET’s Build a Fraction stand-alone sim (based on the Build
a Fraction screen described above but also allows for mixed numbers and
includes the Fraction Lab screen). Participating teachers felt the Fraction
Lab screen would be useful for students to engage with, but did not yet want
students exposed to mixed numbers."
One way this screen was used was when given the task to compare fractions, for example, 1/3 and 1/5. They could build the two fractions side-by-side in the Fraction Lab, which you cannot do in the Intro screen (you can only build one at a time). Similarly, teachers gave a "target" fraction of their choosing (based on the context of a problem) and students could build that fraction in the Fraction Lab, then build an equivalent fraction. It's similar to what is done in the game screen, but with the teacher/students determining what the target fraction is, and being able to lay them out next to each other to discuss was really important. I think that's one of the main strengths of that screen -- the ability to build multiple fractions and examine them side-by-side. 
I would absolutely include Fraction Lab in the HTML5 sim.

**Comment by amanda-phet** [comment]
Thank you so much @krhensberry ! It's really useful to hear how teachers use that screen.

We decided in the 6/22/17 meeting to move forward with Intro, Build a Fraction, and Fraction Lab (no mixed numbers) for this sim, and hopefully a second future sim will include mixed numbers. The Equality Lab might need to be ported and added to Fraction Matcher since those two screens make sense together.

**Comment by amanda-phet** [comment]
The decision (for now), is to have @veillette and his team port the Intro, build a fraction, and fraction lab screens into the HTML5 Fractions Intro sim. 

The HTML5 fractions suite could look like this: 

Sim (1) - Fractions Intro
1. Intro
2. Build a Fraction game
3. Fraction Lab (no mixed numbers)
 
Sim (2) - Mixed Numbers
1. Intro (with mixed numbers toggle? Tricky design, but worth considering) 
2. Build a Mixed Number game
3. Fraction Lab (including mixed numbers)

Sim (3) - Fraction Equality 
1. Equality Lab - Perhaps as the first screen, or perhaps at the end as a Lab screen? This screen should probably be paired with Fraction Matcher in some capacity. 
2. Fraction Matcher game

**Comment by krhensberry** [comment]
Sounds good. I like the idea of a mixed numbers toggle for Intro... Agreed that it might be tricky in terms of design but certainly interesting! There has to be a way to indicate what the whole is. Let me know if you go that route and want any input. 
 A couple of other thoughts:
1. I've only ever heard the term "mixed number" not "mixed fraction" (in that it is a whole number and a fraction - hence, mixed). Maybe I've missed something (possible!) but maybe double check that language.
2. I'll throw out there again since you all are doing this port (even though I know you've heard it before) the issue with different areas representing the same fraction in Fraction Matcher. This is technically incorrect and is often discussed as an area of misconception for students. If the whole isn't the same, the fraction isn't the same, even if they are called by the same name (e.g., 2/3), because it is 2/3 of _something_. Happy to discuss more, or help come up with new game challenges, if this is something you all decide to pursue.

**Comment by amanda-phet** [comment]
@krhensberry said
>I've only ever heard the term "mixed number" not "mixed fraction" (in that it is a whole number and a fraction - hence, mixed). Maybe I've missed something (possible!) but maybe double check that language.

Thank you for catching that- that was totally a mistake on my part!
