### ISSUE TITLE
Test simulation on iPad2 and Report results

### ISSUE THREAD

**Issue by veillette** [phetsims/fractions-intro#83]
This issue will track the performance on the iPad2 using the requirejs version of the simulation on master.

**Comment by coledu** [comment]
After I tested the simulation on the ipad these are all the issues that I have noticed:
- The beaker tab takes the longest to load.
- The animation of pieces to/from the bucket is especially slow in beaker.
- Animation when max is decreased does not work on the ipad for beaker. 
- It seem like the denominator in the cake is taking a lot of time to update. This might be because we are moving the cake and trying to find the correct z order. But the bottom line is it is taking a long time.
- I was so how able when I was decreasing the max and then hit the reset button multiple time I got this. Picture below:

![image](https://user-images.githubusercontent.com/26030529/27751600-0b772ba6-5dab-11e7-9160-40f209536116.png)
