### ISSUE TITLE
Including different denominators

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/fractions-intro#94]
When pieces of only one size are included in the original sims, it is supported to place them anywhere in "slots":
![fractions-split](https://user-images.githubusercontent.com/480878/37141016-ec869f5c-2270-11e8-819e-90a982c73ad3.PNG)

However when different sizes/denominators are supported, it is not possible to place them "anywhere", and it appears forced to be placed in a contiguous order:
![fractions-contiguous](https://user-images.githubusercontent.com/480878/37141038-fedae08c-2270-11e8-97c0-d37f04d5f278.PNG)

Furthermore, it doesn't appear to be possible to remove individual pieces in this case (thus the presence of an "undo" button that removes the last piece).

These seem like two fundamentally different UI behaviors, so I'm curious if this would stay the same. Mixed numbers are only supported in the 2nd (multiple different sizes) UI, so I don't understand what adding "mixed numbers" support to the fractions-intro view/model would exactly mean.

**Comment by ariel-phet** [comment]
These questions are best answered by @amanda-phet

**Comment by amanda-phet** [comment]
In the Build a Fraction game screens and Lab screen, want to be able to move around whole fraction, so the pieces need to glue together and come out with undo. We also want to be able to see how much space you have left in the whole if you are adding pieces of different sizes, so that contiguous order is necessary to achieve that. 

In the Intro screens, want to be able to see that the fraction pieces can be arranged any way and the value of the fraction is the same. Since we don’t need to move those fractions around, the individual pieces can easily be moved. 

I hope that clarifies things a bit and explains why we have two different UI behaviors. 

>Mixed numbers are only supported in the 2nd (multiple different sizes) UI, so I don't understand what adding "mixed numbers" support to the fractions-intro view/model would exactly mean.

For the fractions-intro view/model, this means we are adding a representation, but we are not changing the UI. 

If you want to look over the designs some more let me know and we can zoom. That might be the easiest way to discuss the changes we are making in this port. This document will also be helpful: https://docs.google.com/document/d/1tq09ZpmGOVHVqHnDai351-TSmY_NQbVo6P4PzSEmQpw/edit
