### ISSUE TITLE
Big picture for fractions sims

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/fractions-intro#95]
I've been looking into creating repositories for fractions sims, but I don't see too much information on the individual sims. I'm assuming creating `fractions-common` as a repository for shared code would be needed?

The design documents I have access to (from the Fractions Suite HTML5 folder) are:

- Fractions Intro (https://docs.google.com/document/d/1hwHRO47ZLnyM5HYSDy7qOMVjGs3zF0PzVmGN6n8swjE/edit)
- Fractions Equality (https://docs.google.com/document/d/1D02YH63dtQtE-EvmZlKXUmBCWAQpoM8FlHYgxRqsYyM/edit)
- Mixed Numbers (https://docs.google.com/document/d/1HuAMCmD7IwHVrhSn7cZq6pZwHrStpFgESEEDan2uCeU/edit)

The docs for Fractions Equality and Mixed Numbers mostly look like stubs, so I'm not sure what would be included in those. I've seen some references to including more screens in Fractions Intro, and splitting other screens out into the other sims.

So I have a few questions:

- It seems there will no doubt be shared code, so can I create `fractions-common` and use it for issues that affect multiple sims (or for almost all issues, similar to how `area-model-common` has worked)?
- Are the screens to be included, or the repository names final? If there's a mapping where, for example, "Mixed Numbers" has a list of screens (either new screens, or similar to original Java screens), let me know.
- I'm not particularly sure what to work on now. I'm not confident that fractions-intro's model would use the "mixed numbers" as noted in https://github.com/phetsims/fractions-intro/issues/94.
- How will `fraction-matcher` fit in?
- I'm aware of 6-7 potential screens:
  - Java Fractions Intro has "Intro", "Build a Fraction", "Equality Lab" and "Matching Game"
  - Java Build a Fraction has "Build a Fraction", "Mixed Numbers" and "Fraction Lab"
  - The "Build a Fraction" screens seem slightly different?
  - It seems `fraction-matcher` is the "Matching Game" screen?
  - Are there new screens, or are things going to be mostly ports of those existing screens (modified, of course)?

**Comment by ariel-phet** [comment]
@jonathanolson I believe @amanda-phet has most of these decisions documented, just not in the design doc currrently (I believe she has notes in an .ai file and such).

**Comment by amanda-phet** [comment]
> It seems there will no doubt be shared code, so can I create fractions-common and use it for issues that affect multiple sims (or for almost all issues, similar to how area-model-common has worked)?

I think this is probably a good idea. There is possibly one sim with re-used screens, but even sims that have different screens will have pretty minor changes between them.

>Are the screens to be included, or the repository names final? If there's a mapping where, for example, "Mixed Numbers" has a list of screens (either new screens, or similar to original Java screens), let me know.

I believe so, as of today 3/12/18 :) Maybe I should summarize this in a doc so I can get to your other questions right now. Update: Here is the link to a doc with the mappings: https://docs.google.com/document/d/1tq09ZpmGOVHVqHnDai351-TSmY_NQbVo6P4PzSEmQpw/edit 

>How will fraction-matcher fit in? 

The "Fractions" screen (1st screen) in Fraction Matcher will be used as the sole game screen in "Fractions: Equality". 


Please feel free to revisit the design docs linked above, as they have a few guiding screenshots  from design discussions. They are still called "wireframe" right now because they might have some inconsistencies and aren't fully pixel-polished, but they should give you an idea of the direction we are heading. I need to spend a good chunk of time describing some of the interactions that have changed, so I'll keep you posted about that (likely tomorrow if I can prioritize it, but maybe Wednesday as I'm still catching up). 

>I'm not particularly sure what to work on now. I'm not confident that fractions-intro's model would use the "mixed numbers" as noted in #94. 

If you look at the wireframe mockups in the design docs, that might give you an idea about the underlying models that we will need. But you're correct those are two different models for necessary reasons that I'll comment on in #94 . We aren't changing the model for Fractions: Intro from the original when it comes to building fractions. Fractions: Mixed Numbers will need to display a mixed number representation but it won't be interactive, so that should be fairly simple. There will be some tweaks to the model in the Lab screens but not to the building fraction part as you've pointed out. 

Hope this is helpful for now!
